Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 


Var
// Seção de Declarações das variáveis 
 a , b : inteiro
 n : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreval(" Escreva dois numeros")
  leia (a,b)
  
  n<- (a+b)*0.45
  
  escreval("o resultado do calculo é ",a," é ",n,"")

Fimalgoritmo